name: siscont_restaurantes
description: Aplicativo mobile em Flutter para gerenciar restaurantes.
version: 0.1.0
environment:
  sdk: '>=2.17.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  sqflite: ^2.0.0+4
  path_provider: ^2.0.11
  path: ^1.8.2
  supabase_flutter: ^1.10.0
  connectivity_plus: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

dependency_overrides:
  sign_in_with_apple: null
  sign_in_with_apple_platform_interface: null
  sign_in_with_apple_web: null

  